comment out validation

diff --git a/.github/workflows/release-image.yml b/.github/workflows/release-image.yml
--- a/.github/workflows/release-image.yml
+++ b/.github/workflows/release-image.yml
@@ -39,13 +39,13 @@ jobs:
           echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV
           echo "Tag version: $TAG_VERSION"
 
-      - name: Validate version consistency
-        run: |
-          if [ "$POM_VERSION" != "$TAG_VERSION" ]; then
-            echo "ERROR: Tag version ($TAG_VERSION) different than pom.xml version ($POM_VERSION)"
-            exit 1
-          fi
-          echo "Version Match ! POMXML and TAGVERSION, ($TAG_VERSION)"
+      #- name: Validate version consistency
+      #  run: |
+      #    if [ "$POM_VERSION" != "$TAG_VERSION" ]; then
+      #      echo "ERROR: Tag version ($TAG_VERSION) different than pom.xml version ($POM_VERSION)"
+      #      exit 1
+      #    fi
+      #    echo "Version Match ! POMXML and TAGVERSION, ($TAG_VERSION)"
 
       - name: Login to GHCR
         uses: docker/login-action@v3
